return {
    -- {
    -- 	"folke/trouble.nvim",
    -- 	opts = {},
    -- 	cmd = "Trouble",
    -- 	keys = {
    -- 		{
    -- 			"<leader>!x",
    -- 			"<cmd>Trouble diagnostics toggle<cr>",
    -- 			desc = "Diagnostics (Trouble)",
    -- 		},
    -- 		{
    -- 			"<leader>!X",
    -- 			"<cmd>Trouble diagnostics toggle filter.buf=0<cr>",
    -- 			desc = "Buffer Diagnostics (Trouble)",
    -- 		},
    -- 		{
    -- 			"<leader>!s",
    -- 			"<cmd>Trouble symbols toggle focus=false<cr>",
    -- 			desc = "Symbols (Trouble)",
    -- 		},
    -- 		{
    -- 			"<leader>!l",
    -- 			"<cmd>Trouble lsp toggle focus=false win.position=right<cr>",
    -- 			desc = "LSP Definitions / references / ... (Trouble)",
    -- 		},
    -- 		{
    -- 			"<leader>!L",
    -- 			"<cmd>Trouble loclist toggle<cr>",
    -- 			desc = "Location List (Trouble)",
    -- 		},
    -- 		{
    -- 			"<leader>!Q",
    -- 			"<cmd>Trouble qflist toggle<cr>",
    -- 			desc = "Quickfix List (Trouble)",
    -- 		},
    -- 	},
    -- },
}
